# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('camera', models.CharField(blank=True, choices=[('Nikon', 'NK'), ('Cannon', 'CN')], max_length=50, null=True)),
                ('services', models.CharField(blank=True, choices=[('Portraits', 'P'), ('Weddings', 'W')], max_length=50, null=True)),
                ('photo_styles', models.CharField(blank=True, choices=[('Old', 'O'), ('New', 'N'), ('Modern', 'M')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
