# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
