# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20171206_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], max_length=50, null=True),
        ),
    ]
